### ISSUE TITLE
Package "OpenVPN-OpenSSL" - Kernel mismatch

### ISSUE THREAD

**Issue by EpicLPer** [OnionIoT/OpenWRT-Packages#71]
# What package does this bug affect?

openvpn-openssl

# **Describe the bug**

Trying to install the above package simply results in the following error:
```
Downloading http://repo.onioniot.com/omega2/packages/base/openvpn-openssl_2.4.5-4_mipsel_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for openvpn-openssl:
 *      kernel (= 4.14.81-1-d38bb0cccb6c2f5c91562ebf1fb26fa2) *
 * opkg_install_cmd: Cannot install package openvpn-openssl.
```

# **To Reproduce**

1. Disable OpenWRT repos (if enabled) and use `opkg update`
2. Via Terminal type `opkg install openvpn-openssl`
3. The error message will appear.

# **Expected behavior**
The package should install.

# **Screenshots or Console output**
```
Downloading http://repo.onioniot.com/omega2/packages/base/openvpn-openssl_2.4.5-4_mipsel_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for openvpn-openssl:
 *      kernel (= 4.14.81-1-d38bb0cccb6c2f5c91562ebf1fb26fa2) *
 * opkg_install_cmd: Cannot install package openvpn-openssl.
```

# **Version Info (please complete the following information):**
 - Firmware version: 0.3.4 b257
 - Package name: openvpn-openssl
 - Package Version: 2.4.5-4
 - Repo branch (if applicable): Official Onion Repo

# **Additional context**
I've also tried to install via the official OpenWRT repos, however I'm getting the same error message.

**Comment by greenbreakfast** [comment]
@EpicLPer thanks for making a github issue. 
We will look into this - but I think your best bet will be using the beta 22.03.5 firmware when it's ready for the Omega2 LTE

**Comment by EpicLPer** [comment]
> @EpicLPer thanks for making a github issue. We will look into this - but I think your best bet will be using the beta 22.03.5 firmware when it's ready for the Omega2 LTE

Will definitely try it out 👀 Already excited for it.

**Comment by greenbreakfast** [comment]
To close this out:
* When using the v0.3.4 firmware, the `openvpn-openssl` package does not install because it depends on a version of the kernel compiled in a specific way. This specifically compiled kernel is provided by OpenWRT. An Omega2 device running v0.3.4 firmware has a kernel compiled by Onion that is configured differently. See the [Installing Kernel Modules section in our opkg docs article](https://docs.onion.io/omega2-docs/using-opkg.html) for more details.

Best possible way forward
* Use the beta 22.03.5 firmware since it's now ready for the Omega2 LTE - added as part of #70 - since it's much newer and doesn't have this same issue

I'll close this issue, but feel free to reopen it anytime!
